meta_product_name: "TraQ"
meta_title: "Traq - Helping People in an Emergency"
meta_description: "Connecting people in times of emergency"
meta_image: "traq_logo.png"
# Giving people a sense of mind
# A sense of peace in an emergency
# Find safety in times of emergency
